# -*- encoding: utf-8 -*-
{
    'name': 'Asterisk Calls',
    'version': '12.0.2.4',
    'author': 'Odooist',
    'price': 350.0,
    'currency': 'EUR',
    'maintainer': 'Odooist',
    'support': 'odooist@gmail.com',
    'license': 'OPL-1',
    'category': 'Phone',
    'summary': 'Asterisk and Odoo integration',
    'description': """
    """,
    'depends': ['mail', 'bus', 'board', 'contacts', 'remote_agent'],
    'data': [
        'security/common.xml',
        'security/service/security.xml',
        'security/service/ir.model.access.csv',
        'security/user/security.xml',
        'security/user/ir.model.access.csv',
        'security/admin/security.xml',
        'security/admin/ir.model.access.csv',
        'views/views.xml',
        'views/resources.xml',
        'views/call.xml',
        'views/library.xml',
        'views/tag.xml',
        'views/user.xml',
        'views/channel.xml',
        'views/res_partner.xml',
        'views/res_users.xml',
        'views/settings.xml',
        'views/ir_cron.xml',
        'views/templates.xml',
        'views/about.xml',
        'views/website_templates.xml',
        'views/callback.xml',
        # statistics
        'reports/incoming.xml',
        'reports/outgoing.xml',
        # Reports
        'reports/reports.xml',
        'reports/calls_report.xml',
        # Wizards
        'wizard/call.xml',
        # Data
        'data/channel.xml',
        'data/agent.xml',
        ],
    'demo': [],
    "qweb": ['static/src/xml/*xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/logo1.png'],
}
